# fly.toml app configuration file generated for slacker-news on 2024-03-07T15:36:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slacker-news'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.22.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
